server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: skufify-sharing-service
  config:
    import: optional:file:.env[.properties], keystore/s3keys.properties

  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

grpc:
  client:
    AuthClientGrpcService:
      address: ${GRPC_AUTH_CLIENT_HOST}:${GRPC_AUTH_CLIENT_PORT}
      negotiation-type: plaintext

logging:
  level:
    org.springframework.security.web.FilterChainProxy: ERROR
    ru.improve.unboundedSound: ERROR

yandex-storage:
  s3:
    service-endpoint: https://storage.yandexcloud.net
    signing-region: ru-central1
    music-bucket-name: openfy-music-bucket

select-limits:
  artistsPerPage: 20
  albumsPerPage: 20
  tracksPerPage: 20