drop table tracks;
create table tracks (
    id int4 primary key generated by default as identity,
    name varchar(50) not null,
    author_name varchar(50),
    durability int,
    created_date date,
    size int not null,
    hash varchar(512) unique,
    uploader_id int not null
)