create table track (
    id bigint primary key generated by default as identity,
    name varchar(50) not null,
    author_name varchar(50),
    size int not null,
    hash varchar(512) unique,
    uploader bigint not null
)