create table artists (
    id int primary key generated by default as identity,
    name varchar(100) not null unique,
    cover_url text ,
    uploader bigint not null,
    upload_date date not null default current_date
);

create table albums (
    id int primary key generated by default as identity,
    name varchar(100) not null unique,
    artist int references artists(id) not null,
    cover_url text,
    uploader bigint not null,
    upload_date date not null default current_date
);

create table tracks (
    id bigint primary key generated by default as identity,
    name varchar(50) not null unique,
    artist int references artists(id) not null,
    album int references albums(id),
    format varchar(5) not null ,
    size int not null,
    key varchar(512) not null unique,
    uploader bigint not null,
    upload_date date not null default current_date
);
